 
[tasks.install-release]
dependencies = ["websockify","vnc-release"]

 
[env]
INSTALL_PATH= "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/build"
WEBSOCKIFY="axum-websockify"
VNC="webvnc"
RDP="webrdp"
SSH="webssh"

 
 
[tasks.vnc-release]
dependencies = ["install-dir"]
script = '''
cd webvnc && cargo make install-release && cd ..
'''

 

[tasks.websockify]
dependencies = ["install-dir"]
script = '''
cd ${WEBSOCKIFY} && cargo build --release --features ssl && cp ./target/release/${WEBSOCKIFY} ${INSTALL_PATH}/
'''

[tasks.install-dir]
script = '''
mkdir -p ${INSTALL_PATH}
cp assets/* ${INSTALL_PATH}
'''
 
 
 
